drivers: iio: smi330: Fix I2C probe() API mismatch
With kernel >= v6.10 the `i2c_device_id` parameter was dropped from
smi330_i2c_probe(). See

commit 03c835f498b5 ("i2c: Switch .probe() to not take an id parameter")

For kernel's >= v6.10 this will result in

drivers/iio/imu/smi330/smi330_i2c.c:171:11: error: incompatible
  function pointer types initializing 'int (*)(struct i2c_client *)'
  with an expression of type 'int (struct i2c_client *, const struct
  i2c_device_id *)' [-Wincompatible-function-pointer-types]
  171 |         .probe = smi330_i2c_probe,
      |                  ^~~~~~~~~~~~~~~~
1 error generated.

Fix this by checking the kernel version information.

Signed-off-by: Dirk Behme <dirk.behme@de.bosch.com>